version: 2.1

cache_key: &cache_key cannon-deps-20201228-{{ checksum "go.sum" }}

jobs:
  lint-build:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - restore_cache:
          name: Restore dependency cache
          keys:
            - *cache_key
      - run:
          name: Install dependencies
          command: make setup
      - save_cache:
          name: Cache dependencies
          key: *cache_key
          paths:
            - ~/go/pkg
      - run:
          name: Run linter
          command: make lint
      - run:
          name: Build cannon
          command: make build
      - run:
          name: Run tests
          command: make test-ci

workflows:
  lint-build:
    jobs:
      - lint-build
